# Generated by Django 3.1.7 on 2021-03-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_auto_20210328_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackbots',
            name='agent',
            field=models.TextField(default='afafa', max_length=255, verbose_name='выдаваемый агент'),
        ),
    ]
