# Generated by Django 3.1.7 on 2021-03-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_auto_20210328_0813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='slackbots',
            options={'verbose_name': 'SlackBot', 'verbose_name_plural': 'SlackBots'},
        ),
        migrations.AddField(
            model_name='slackbots',
            name='channel',
            field=models.CharField(default='#general', help_text='внимание, бот должен быть авторизован в данном канале', max_length=255, verbose_name='канал бота'),
        ),
        migrations.AddField(
            model_name='slackbots',
            name='flag',
            field=models.CharField(choices=[('work1', 'Задача №1'), ('work2', 'Задача №1')], default='work1', max_length=5),
        ),
    ]
