# Generated by Django 3.1.7 on 2021-03-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0008_auto_20210328_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='public_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
