# Generated by Django 3.1.7 on 2021-03-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0010_posts_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slackbots',
            name='agent',
        ),
        migrations.AddField(
            model_name='slackbots',
            name='delay',
            field=models.IntegerField(default=3, help_text='задержка между отправками сообщении', verbose_name='задержка для бота'),
        ),
        migrations.AddField(
            model_name='slackbots',
            name='editor_text',
            field=models.TextField(default='Всем привет! На нашем хабре появились новые статьи.\n Не забудьте посмотреть:\n\n'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='public_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата захвата'),
        ),
        migrations.AlterField(
            model_name='slackbots',
            name='channel',
            field=models.CharField(default='#general', help_text='внимание, бот должен быть авторизован на данном канале', max_length=255, verbose_name='канал бота'),
        ),
    ]
