# Generated by Django 3.1.7 on 2021-03-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0011_auto_20210328_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slackbots',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='slackbots',
            name='host',
        ),
        migrations.RemoveField(
            model_name='slackbots',
            name='url',
        ),
        migrations.AddField(
            model_name='slackbots',
            name='task',
            field=models.CharField(choices=[('work1', 'Задача №1'), ('work2', 'Задача №2')], default='work1', max_length=5, verbose_name='задача'),
        ),
    ]
