# Generated by Django 3.1.7 on 2021-03-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0012_auto_20210328_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParseDelay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='task', help_text='для захвата модели', max_length=255)),
                ('parse_delay', models.IntegerField(default=5, help_text='задержка в минутах между запросами на сайт', verbose_name='задержка для парсинга')),
            ],
            options={
                'verbose_name': 'Задержка парсинга',
                'verbose_name_plural': 'Задержка парсинга',
            },
        ),
    ]
