# Generated by Django 3.1.7 on 2021-03-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0013_parsedelay'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='task1', help_text='для захвата модели', max_length=255)),
                ('task_id', models.CharField(help_text='для захвата модели', max_length=255)),
                ('parse_delay', models.IntegerField(default=5, help_text='задержка в минутах между запросами на сайт', verbose_name='задержка для парсинга')),
            ],
            options={
                'verbose_name': 'Задержка парсинга',
                'verbose_name_plural': 'Задержка парсинга',
            },
        ),
        migrations.DeleteModel(
            name='ParseDelay',
        ),
    ]
