# Generated by Django 3.1.7 on 2021-03-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0014_auto_20210329_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskconfig',
            name='mode',
            field=models.CharField(choices=[('mode1', 'Отправить сообщение сразу, если есть новй контент'), ('mode2', 'Отправить сообщение один раз в час, если есть новй контент'), ('mode3', 'Отправить сообщение один раз в день, если есть новй контент'), ('mode4', 'Отправить сообщение один раз в неделю, если есть новй контент')], default='mode1', max_length=5, verbose_name='задача'),
        ),
    ]
