# Generated by Django 3.1.7 on 2021-04-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0018_auto_20210402_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackbots',
            name='bot_tags',
            field=models.TextField(default=1, help_text='Для задачи №2 введите теги через запятую'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slackbots',
            name='delay',
            field=models.IntegerField(default=3, verbose_name='Номер задачи'),
        ),
        migrations.AlterField(
            model_name='slackbots',
            name='task',
            field=models.CharField(choices=[('work1', 'Задача №1'), ('work2', 'Задача №2')], default='work1', max_length=5, verbose_name='Задача'),
        ),
    ]
