# Generated by Django 3.1.7 on 2021-04-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0019_auto_20210402_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskconfig',
            name='name',
        ),
        migrations.AddField(
            model_name='taskconfig',
            name='task',
            field=models.CharField(choices=[('task1', 'Задача №1'), ('task2', 'Задача №2')], default='task1', max_length=5, verbose_name='Задача'),
        ),
    ]
