# Generated by Django 3.1.7 on 2021-04-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0022_auto_20210404_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackbots',
            name='bot_tags',
            field=models.CharField(default='Блог компании SkillFactory,', help_text='Для задачи №2 введите теги через запятую', max_length=255, null=True),
        ),
    ]
